#!/usr/bin/env node
/** Generate site/langs.js and site/build-meta.js for local use.
 *
 * Both files are gitignored (CI writes them on deploy), so a fresh clone
 * served with `python -m http.server` has no language registry and the
 * site language picker degrades. This script regenerates them from
 * languages.json, mirroring writeLangs()/writeBuildMeta() in site/build.js.
 * Called by 启动学习环境.bat before starting the local server.
 */
const fs = require('fs');
const path = require('path');

const siteDir = path.join(__dirname, '..', 'site');
const regPath = path.join(__dirname, '..', 'languages.json');

let langs = [{ code: 'en', native: 'English' }];
try {
  const reg = JSON.parse(fs.readFileSync(regPath, 'utf8'));
  langs = reg.languages
    .filter(l => l.source || l.ci)
    .map(l => ({ code: l.code, native: l.native }));
} catch (e) {
  console.warn('languages.json unreadable, writing English-only fallback');
}

fs.writeFileSync(
  path.join(siteDir, 'langs.js'),
  '// Auto-generated by scripts/gen_site_meta.js — do not edit.\n' +
    'window.AIFS_LANGS = ' + JSON.stringify(langs) + ';\n',
  'utf8'
);
fs.writeFileSync(
  path.join(siteDir, 'build-meta.js'),
  '// Auto-generated by scripts/gen_site_meta.js — do not edit.\n' +
    'window.__AIFS_REF = "main";\n',
  'utf8'
);
console.log('wrote site/langs.js (' + langs.length + ' languages) and site/build-meta.js');
